spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: server-config-dev
eureka:
  instance:
    hostname: eureka8201.com #eureka的主机名
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

---
server:
  port: 8202

spring:
  profiles: test
  application:
    name: server-config-test
eureka:
  instance:
    hostname: eureka8002.com #eureka的主机名
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

